# General information
title: Introduction to Quantum Computing for Business
theme: just-the-docs


# SEO information (https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)
description: Everything you should know about the applications of quantum technology.
# tagline : # Optional SEO argument, will appear in title of html page.
author:
  name: Koen Groenland
### additionally, add the following to individual posts: image; title; description.



# Rendering setings
markdown: kramdown
url: https://koengr.github.io
#baseurl: QCforBusiness  ## ENABLE FOR GITHUB without custom domain!


# Use customized colors
color_scheme: mycolors  


# Fancy logo (appears on top-left above navigation)
logo: "/site-img/lineart-header-wide.webp"   # seems bugged - just-the-docs adds untranslated {base_url} in css?
favicon_ico: "/site-img/linaert-atom-favicon.ico"
locale: en_GB

# Extra plugins, mainly for search engine optimization
plugins:
  - jekyll-seo-tag      # No need to add {% seo %} in head.html when using just-the-docs, it's included by default.
  # - jekyll-analytics
  # - jekyll-toc




# Define Jekyll collections.
# Example: Define a collection named "NAME", its documents reside in the "_NAME" directory
collections:
  essentials:
    permalink: "/:collection/:path/"
    output: true
  applications:
    permalink: "/:collection/:path/"
    output: true
  advanced:
    permalink: "/:collection/:path/"
    output: true
  resources:
    permalink: "/:collection/:path/"
    output: true

# Define which collections are used in just-the-docs
just_the_docs:
  collections:
    essentials:
      name: "Part 1: The essentials"
      # Exclude the collection from the navigation (true/false)
      nav_exclude: False
      # Fold the collection in the navigation
      nav_fold: false  
    applications:
      name: "Part 2: Understanding the applications"
    advanced:
      name: "Part 3: Going deeper"
    resources:
      name: "Part 4: Recommended resources"

# Define callout boxes
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: faintgray
    #color: grey-dk
  new:
    color: yellow
  graycallout:
    color: faintgray
  redcallout:
    color: faintred
  greencallout:
    color: green
  recommendationbox:
    title: See also
    color: testgray

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

# for jekyll-toc package? Doens't seem to actually work :(.
toc:
  min_level: 1
  max_level: 2
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: koens-toc
  list_class: section-nav-koen
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-