title: Introduction to Quantum Computing for Business
description: This is a description - where does it appear?
theme: just-the-docs

url: https://koengr.github.io/QCforBusiness

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
